version: '3'

services:
  database:
    tty: true
    build:
      context: .
      dockerfile: ./.deployment/database/Dockerfile
    ports:
      - 9001:9001
    depends_on:
      - h2
    links:
      - h2:db

  h2:
    image: oscarfonts/h2
    ports:
      - 1521:1521
      - 81:81
    volumes:
      - h2_data:/opt/h2-data

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

volumes:
  h2_data:
